### ISSUE TITLE
Using a matrix as weights in fasterFocal

### ISSUE THREAD

**Issue by MPilar123** [adamlilith/fasterRaster#40]
Hi Adam,
I find your package really impressive. It is the fastest I guess. 
However, I try to use the function fasterFocal with a specific matrix created with the base function "matrix" and it doesn't work.
The matrix used is created as follows:
m5 <- matrix(c(1,NA,1,NA,1,NA,1,1,1,NA,1,1,NA,1,1,NA,1,1,1,NA,1,NA,1,NA,1), nrow=5, ncol=5)
And I just try to do the following, with a very big raster 'r' object:
ff1 <- fasterFocal (r, w=m5, fun=max)

I think this could be because the class of a matrix is "matrix" "array" and hence the condition class(w) == "matrix" is not met.
I have not found any way of producing a matrix with its actual class being only "matrix".
Could you consider checking this possible bug?
Thanks a lot,

MPilar

**Comment by adamlilith** [comment]
Hi MPilar,

Thank you for the message.  I was able to recreate the error you got.  Part of the issue may have been using class()… which I have learned since I created fasterRaster isn’t good to use in functions, so I went ahead and changed almost all uses of class() to inherits() (the preferred method) in the package.  So thanks for that!

However, I think the issue you’re wrestling with is caused by the fact that your weights raster has NA values. In this case, use the na.rm=TRUE argument:

ff1 <- fasterFocal (r, w=m5, fun=max, na.rm=TRUE)

Note that if you use just one core, you may get a slightly different output (the lowest value will be -Inf), whereas is you use more than one core, it should be numeric.

I added an example of how to do this to the function documentation.  So, thanks again!

Adam

PS I pushed the new version of fasterRaster 7.0.1, with inherits() onto GitHub.

From: MPilar123 ***@***.***>
Sent: Friday, August 5, 2022 3:12 AM
To: adamlilith/fasterRaster ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [adamlilith/fasterRaster] Using a matrix as weights in fasterFocal (Issue #40)


Hi Adam,
I find your package really impressive. It is the fastest I guess.
However, I try to use the function fasterFocal with a specific matrix created with the base function "matrix" and it doesn't work.
The matrix used is created as follows:
m5 <- matrix(c(1,NA,1,NA,1,NA,1,1,1,NA,1,1,NA,1,1,NA,1,1,1,NA,1,NA,1,NA,1), nrow=5, ncol=5)
And I just try to do the following, with a very big raster 'r' object:
ff1 <- fasterFocal (r, w=m5, fun=max)

I think this could be because the class of a matrix is "matrix" "array" and hence the condition class(w) == "matrix" is not met.
I have not found any way of producing a matrix with its actual class being only "matrix".
Could you consider checking this possible bug?
Thanks a lot,

MPilar
