### ISSUE TITLE
CRAN has retired grass7 and rgdal

### ISSUE THREAD

**Issue by jamesdalg** [adamlilith/fasterRaster#55]
CRAN has retired rgdal, making installation not possible with install_github().

**Comment by jamesdalg** [comment]
https://grass.osgeo.org/news/2023_06_05_retirement_of_rgrass7/

**Comment by adamlilith** [comment]
Sorry, I can't fix that for the version on the `main` branch since it requires the use of the `raster` package, which in turn requires `rgdal`. However, you can still get old versions of `rgdal` (and `raster`) from the "archive" page on CRAN (ex: https://cran.r-project.org/web/packages/rgdal/index.html), then manually install the package from the gzip file.

This said, the new version of `fasterRaster` on branch `intuitive_fasterRaster` does not need `rgdal`. Rather, it works with GRASS and emulates functions in `terra` (e.g., terra has `buffer()`, `focal()`, `crop()`, etc., and the new version of `fasterRaster` does, too. If you know `terra`, you basically know `fasterRaster`.

You should be able to get this new version (as of the date posted here) using:

`devtools::install_github('adamlilith/fasterRaster@intuitive_fasterRaster')`

Please note that it's still in active development, but most of the functions work as intended. You can see table of contents of functions, and link to a quick tutorial, using `?fasterRaster`.

Best!
