### ISSUE TITLE
R Version 4.3.2 Issues

### ISSUE THREAD

**Issue by daviskec** [adamlilith/fasterRaster#56]
Hi, I'm trying to install fasterRaster using the given code:
`remotes::install_github('adamlilith/fasterRaster', dependencies=TRUE)`
But I'm running into issues due to my R version (4.3.2). Initally I got this error:
`Downloading GitHub repo adamlilith/fasterRaster@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/adamlilith/fasterRaster/tarball/HEAD' failed`
Then I removed the dependencies argument, got a little further, and then got this error message:
`Installing package into ‘C:/Users/katie/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
ERROR: dependencies 'rgrass7', 'rgdal' are not available for package 'fasterRaster'
* removing 'C:/Users/katie/AppData/Local/R/win-library/4.3/fasterRaster'
Warning messages:
1: packages ‘rgdal’, ‘rgrass7’ are not available for this version of R

Versions of these packages for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In i.p(...) :
  installation of package ‘C:/Users/katie/AppData/Local/Temp/Rtmp8cZqtS/file30f477e11e79/fasterRaster_0.7.2.tar.gz’ had non-zero exit status`

I know rgdal is being phased out, and rgrass7 appears to have been replaced by rgrass. Are there any plans to update fasterRaster to work with newer versions/packages?

**Comment by adamlilith** [comment]
Thanks for your interest in this package!  You are correct, the main branch is old and won't install because some of the packages it depended upon have been retired as of last year. *However*, I am developing a new version of **fasterRaster** that works and feels like the **terra** package.

[fasterRaster "intuitive" branch](https://github.com/adamlilith/fasterRaster/tree/intuitive_fasterRaster)

You will see (in the `README`) how to install the package and use this new version.

Please note that the hang-up between me and getting an official release is how vectors work. Mainly, right now, if you subset a vector (e.g., to get the outline of a US state from a vector representing all 50 states), it will either a) work, b) not work as intended, or c) not work. This is a major hang-up, and I may need to rework how vectors work in **fasterRaster** because of it. For now, I suggest using **terra** and/or **sf** to do GIS operations on vectors, then importing results into **fatserRaster** using `fast()`. If you need to, you can export the vectors back to **terra** or **sf** formats using `rast()`, `vect()`, or `st_as_sf()`. Please check back her for any announcements about fixes to the vector issue!

**Comment by daviskec** [comment]
I was able to install the intuitive branch! Thanks for pointing me in the right direction - I haven't downloaded a package from a non-master branch before.

**Comment by daviskec** [comment]
I'm trying to adapt a code I was given that used the old `fasterTopidx() `function. It looks like the equivalent in the intuitive branch is ` topoWetnessIndex()`, so my code now looks like this:

```
faster(grassDir = "C:/Program Files/GRASS GIS 8.3") # change to where GRASS is installed

graster.elev1 <- fasterRaster::fast(paste0(here::here(), "/Spatial_Data/SRTM_elevation/N43W111.SRTMGL1.hgt/N43W111.hgt"), rastOrVect = "raster")
graster.elev2 <- fasterRaster::fast(paste0(here::here(), "/Spatial_Data/SRTM_elevation/N44W111.SRTMGL1.hgt/N44W111.hgt"), rastOrVect = "raster")

cti.1 <- topoWetnessIndex(graster.elev1)
cti.2 <- topoWetnessIndex(graster.elev2)

```
However, when I run the `topoWetnessIndex()` function, I get this error:

`Error in if (type == "raster") { : argument is of length zero`

I'm not sure how to troubleshoot this!

**Comment by adamlilith** [comment]
This is indeed strange... I am guessing for some reason the **GRASS** `r.topidx` module is not working. If you use:

`faster(verbose = TRUE)`

what messages do you get?  (You can call `faster()` multiple times, with the same or different setting.)

Also, if you were to convert the elevation rasters to `GeoTIFF`s beforehand, does that work out?

Thanks!
Adam

**Comment by daviskec** [comment]
Okay, some other weird things started happening so I had to delete the package, restart R and reinstall. 

I saved my elevation file as a .tif using terra, then imported it using `fast()`, then attempted the `topoWetnessIndex() `and got the same error as above.

`faster(verbose = TRUE)` doesn't do anything? It appears to run but there is no output.

**Comment by adamlilith** [comment]
Hmmm... I'm sorry about this!  Is there a way you could send me a raster, or a portion thereof? You can get my email address from here: https://earthskysea.org/ (click this icon in the upper right of any page):

![image](https://github.com/adamlilith/fasterRaster/assets/7577062/cfc4d9a4-6c9b-43fe-bbef-4a6609141427)

**Comment by adamlilith** [comment]
Running the module in **GRASS**, I found that the `r.topidx` module can only use projected rasters, not unprojected ones (e.g., WGS84):

![image](https://github.com/adamlilith/fasterRaster/assets/7577062/bf268169-7c76-47b8-bace-3686b4574dae)

This is not documented at all in the [help page](https://grass.osgeo.org/grass83/manuals/r.topidx.html) for that module.

I put a catch in the **fasterRaster** `topoWetnessIndex()` function to throw an error if the raster is unprojected. The work-around would be to project the raster, calculate TWI, then project it back.  Here's a code skeleton:

```
# define crs_string as the WKT string for a proejceted coordinate system
crs_string <- <string here>

elev <- fast(file_name)
elev_proj <- project(elev, crs_string)
twi_proj <- topoWetnessIndex(elev_proj)
twi <- project(twi_proj, elev)
writeRaster(twi, new_file_name)
```

Thanks!
